013_objects_on_rails/bloog/config/routes.rb
Bloog::Application.routes.draw do
  get "blog/index"
  root to: "blog#index"
  resources :posts

end

013_objects_on_rails/bloog/app/models/blog.rb
class Blog
  attr_writer :post_source

  def initialize(entry_fetcher=Post.public_method(:all))
    @entry_fetcher = entry_fetcher
  end

  def title
    "Watching Paint Dry"
  end

  def subtitle
    "The trusted source for drying paint news & opinions"
  end

  def new_post(*args)
    post_source.call(*args).tap do |p|
      p.blog = self
    end
  end

  def add_entry(entry)
    entry.save
  end

  def entries
    fetch_entries.sort_by(&:pubdate).reverse.take 10
  end

  private
  def post_source
    @post_source ||= Post.public_method(:new)
  end

  def fetch_entries
    @entry_fetcher.()
  end
end

013_objects_on_rails/bloog/app/models/post.rb
require 'date'
require 'active_record'

class Post < ActiveRecord::Base
  validates :title, presence: true
  attr_accessor :blog

  def publish(clock = DateTime)
    return false unless valid?
    self.pubdate = clock.now
    blog.add_entry(self)
  end

  def picture?
    image_url.present?
  end
end

013_objects_on_rails/bloog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :init_blog

  helper :exhibits

  private
  def init_blog
    @blog = THE_BLOG
  end
end

013_objects_on_rails/bloog/app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    # @blog = Blog.new
    # post1 = @blog.new_post
    # post1.title = "Paint just applied"
    # post1.body = "Paint just applied. It's a lovely orangey-purler"
    # post1.publish
    # post2 = @blog.new_post(title: "Still wet")
    # post2.body = "Paint is still quite wet. No bubbling yet!"
    # post2.publish
  end
end

013_objects_on_rails/bloog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = @blog.new_post
  end

  def create
    @post = @blog.new_post(params[:post])
    if @post.publish
      redirect_to root_path, notice: "Post added!"
    else
      render "new"
    end
  end
end

013_objects_on_rails/bloog/app/helpers/application_helper.rb
module ApplicationHelper
end

013_objects_on_rails/bloog/app/helpers/blog_helper.rb
module BlogHelper
end

013_objects_on_rails/bloog/app/helpers/exhibits_helper.rb
module ExhibitsHelper
  def exhibit(model, context)
    Exhibit.exhibit(model, context)
  end
end

013_objects_on_rails/bloog/app/views/blog/_entry.html.erb
<% entry = exhibit(entry, self) %>
<article>
  <header>
    <p><time pubdate="pubdate"><%= entry.pubdate %></time></p>
    <h3><%= entry.title %></h3>
  </header>
  <p><%= entry.render_body %></p>
</article>

013_objects_on_rails/bloog/app/views/blog/index.html.erb
<h1><%= @blog.title %></h1>
<h1><%= @blog.subtitle %></h1>
<%= render partial: "entry", collection: @blog.entries %>

013_objects_on_rails/bloog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="sidebar two columns">
    <nav>
      <ul>
        <li><%= link_to "New Post...", new_post_path %></li>
      </ul>
    </nav>
  </div>

<%= yield %>

</body>
</html>

013_objects_on_rails/bloog/app/views/posts/_picture_body.html.erb
<figure>
  <img src="<%= post.image_url %>">
  <figcaption><%= post.body %></figcaption>
</figure>

013_objects_on_rails/bloog/app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @post do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :body %>
  <%= lable :image_url, "Picture URL:" %>
  <%= f.text_field :image_url %>
  <%= f.submit %>
<% end %>